// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

function toFloat(str) {
  var result = Number(str);
  if (isNaN(result)) {
    return ;
  } else {
    return result;
  }
}

function cube(x) {
  return x * x * x;
}

function reciprocal(x) {
  if (x !== 0.0) {
    return 1.0 / x;
  }
  
}

function makeDisplayText(s) {
  if (s !== undefined) {
    return "The result is " + s;
  } else {
    return "Invalid input";
  }
}

function method1(input) {
  console.log(makeDisplayText(Belt_Option.map(Belt_Option.map(Belt_Option.flatMap(toFloat(input), reciprocal), cube), (function (param) {
                  return param.toFixed(3);
                }))));
  return /* () */0;
}

method1("0.032");

exports.toFloat = toFloat;
exports.cube = cube;
exports.reciprocal = reciprocal;
exports.makeDisplayText = makeDisplayText;
exports.method1 = method1;
/*  Not a pure module */
