// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");

function stringOfColorSpec(cspec) {
  if (typeof cspec === "number") {
    if (cspec === /* White */0) {
      return "rgb(255, 255, 255)";
    } else {
      return "rgb(0, 0, 0)";
    }
  } else if (cspec.tag) {
    return "rgb(" + (String(cspec[0]) + (", " + (String(cspec[1]) + (", " + (String(cspec[2]) + ")")))));
  } else {
    return "rgb(127, 127, 127)";
  }
}

console.log("rgb(255, 255, 255)");

console.log(stringOfColorSpec(/* RGB */Block.__(1, [
            123,
            242,
            213
          ])));

exports.stringOfColorSpec = stringOfColorSpec;
/*  Not a pure module */
