// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_int32 = require("bs-platform/lib/js/caml_int32.js");

console.log("Hello, BuckleScript and Reason!");

var total = 105;

var bad1 = 0.0;

console.log("The total price is $", total);

function avg(a, b) {
  return (a + b) / 2.0;
}

var result = (3.0 + 4.5) / 2.0;

console.log(result.toFixed(3));

function payment(principle, apr, years) {
  var r = apr / 12.0 / 100.0;
  var n = Caml_int32.imul(years, 12);
  var powerTerm = Math.pow(1.0 + r, n);
  return principle * (r * powerTerm) / (powerTerm - 1.0);
}

var amount = payment(10000.0, -5.0, 30);

console.log("ammount: ", amount.toFixed(3));

function sqr(x) {
  return Caml_int32.imul(x, x);
}

console.log("Average of 3? ", (function (param) {
        return avg(3.9, param);
      }));

var qty = 7;

var price = 15;

exports.qty = qty;
exports.price = price;
exports.total = total;
exports.bad1 = bad1;
exports.avg = avg;
exports.result = result;
exports.payment = payment;
exports.amount = amount;
exports.sqr = sqr;
/*  Not a pure module */
