// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function calDiscount(price, discount) {
  return price * discount / 100.0;
}

function halfOf(param) {
  return calDiscount(param, 50.0);
}

function tenPercentof(param) {
  return calDiscount(param, 10.0);
}

console.log("Half of", halfOf);

console.log(1000.0 * 50.0 / 100.0);

console.log(tenPercentof);

console.log(1000.0 * 10.0 / 100.0);

exports.calDiscount = calDiscount;
exports.halfOf = halfOf;
exports.tenPercentof = tenPercentof;
/*  Not a pure module */
